services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sn_foods
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

  web:
    build: .
    command: /bin/bash /app/entrypoint.sh &&  python /app/manage.py popular_dados  && 

    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app_network

volumes:
  db_data:

networks:
  app_network:
    driver: bridge
