# Generated by Django 5.1.3 on 2024-11-08 20:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('em_preparacao', 'Em Preparação'), ('a_caminho', 'A Caminho'), ('entregue', 'Entregue')], default='pendente', max_length=20)),
                ('data_pedido', models.DateTimeField(auto_now_add=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=90)),
                ('descricao', models.CharField(max_length=130)),
                ('quantidade', models.PositiveIntegerField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.CharField(choices=[('bebida', 'Bebida'), ('sobremesa', 'Sobremesa'), ('salada', 'Salada'), ('acompanhamento', 'Acompanhamento')], default='bebida', max_length=20)),
                ('pedido_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fn_foods.pedido')),
            ],
        ),
    ]
