# Generated by Django 5.1.3 on 2024-11-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fn_foods', '0001_initial'),
    ]

    operations = [
    ]
